name: ExerciseSampleCompose

on:
  push:
    branches:
      - main
    paths:
      - 'health-services/ExerciseSampleCompose/**'
      - '.github/workflows/ExerciseSampleCompose.yml'
  pull_request:
    paths:
      - 'health-services/ExerciseSampleCompose/**'
      - '.github/workflows/ExerciseSampleCompose.yml'

env:
  SAMPLE_PATH: health-services/ExerciseSampleCompose

jobs:
  build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Unit Tests
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: ${{ env.SAMPLE_PATH }}
          arguments: testDebug

      - name: Screenshot Tests
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: ${{ env.SAMPLE_PATH }}
          arguments: verifyRoborazziDebug

      - name: Upload test results and reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: |
            **/build/test-results/*
            **/build/reports/*
            **/out/*
